import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@coinbase/onchainkit/styles.css";
import AppProviders from "./providers";
import TopNav from "./components/TopNav";
import LeftNav from "./components/LeftNav";
import RightHotCommunities from "./components/RightHotCommunities";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProviders>
          <TopNav />
          <div className="mx-auto max-w-6xl px-3 sm:px-6">
            <div className="flex gap-4">
              <aside className="hidden md:block w-56 shrink-0">
                <LeftNav />
              </aside>
              <main className="flex-1 min-w-0">{children}</main>
              <aside className="hidden lg:block w-64 shrink-0">
                <RightHotCommunities />
              </aside>
            </div>
          </div>
        </AppProviders>
      </body>
    </html>
  );
}
